package optional

//go:generate gotemplate "4d63.com/optional/template" Bool(bool)
//go:generate gotemplate "4d63.com/optional/template" Byte(byte)
//go:generate gotemplate "4d63.com/optional/template" Complex128(complex128)
//go:generate gotemplate "4d63.com/optional/template" Complex64(complex64)
//go:generate gotemplate "4d63.com/optional/template" Float32(float32)
//go:generate gotemplate "4d63.com/optional/template" Float64(float64)
//go:generate gotemplate "4d63.com/optional/template" Int(int)
//go:generate gotemplate "4d63.com/optional/template" Int16(int16)
//go:generate gotemplate "4d63.com/optional/template" Int32(int32)
//go:generate gotemplate "4d63.com/optional/template" Int64(int64)
//go:generate gotemplate "4d63.com/optional/template" Int8(int8)
//go:generate gotemplate "4d63.com/optional/template" Rune(rune)
//go:generate gotemplate "4d63.com/optional/template" String(string)
//go:generate gotemplate "4d63.com/optional/template" Uint(uint)
//go:generate gotemplate "4d63.com/optional/template" Uint16(uint16)
//go:generate gotemplate "4d63.com/optional/template" Uint32(uint32)
//go:generate gotemplate "4d63.com/optional/template" Uint64(uint64)
//go:generate gotemplate "4d63.com/optional/template" Uint8(uint8)
//go:generate gotemplate "4d63.com/optional/template" Uintptr(uintptr)

//go:generate gotemplate "4d63.com/optional/template" Time(time.Time)
