// Code generated by gotemplate. DO NOT EDIT.

package optional

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"time"
)

var _Uint8 = time.Time{}

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Uint8 optionalUint8

type optionalUint8 []uint8

const (
	valueKeyUint8 = iota
)

// Of wraps the value in an optional.
func OfUint8(value uint8) Uint8 {
	return Uint8{valueKeyUint8: value}
}

func OfUint8Ptr(ptr *uint8) Uint8 {
	if ptr == nil {
		return EmptyUint8()
	} else {
		return OfUint8(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyUint8() Uint8 {
	return nil
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Uint8) Get() (value uint8, ok bool) {
	o.If(func(v uint8) {
		value = v
		ok = true
	})
	return
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Uint8) IsPresent() bool {
	return o != nil
}

// If calls the function if there is a value wrapped by this optional.
func (o Uint8) If(f func(value uint8)) {
	if o.IsPresent() {
		f(o[valueKeyUint8])
	}
}

func (o Uint8) ElseFunc(f func() uint8) (value uint8) {
	if o.IsPresent() {
		o.If(func(v uint8) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Uint8) Else(elseValue uint8) (value uint8) {
	return o.ElseFunc(func() uint8 { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Uint8) ElseZero() (value uint8) {
	var zero uint8
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Uint8) String() string {
	return fmt.Sprintf("%v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Uint8) MarshalJSON() (data []byte, err error) {
	return json.Marshal(o.ElseZero())
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Uint8) UnmarshalJSON(data []byte) error {
	var v uint8
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfUint8(v)
	return nil
}

// MarshalXML marshals the value being wrapped to XML. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Uint8) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(o.ElseZero(), start)
}

// UnmarshalXML unmarshals the XML into a value wrapped by this optional.
func (o *Uint8) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var v uint8
	err := d.DecodeElement(&v, &start)
	if err != nil {
		return err
	}
	*o = OfUint8(v)
	return nil
}
