name: go
on:
  schedule:
      - cron:  '0 0 * * 0' # every 7 days on Sunday
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go test -race -cover ./...
